# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'AlphabetWar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'FBAudienceNetwork'
  pod 'SwiftEntryKit', '1.2.7'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftMessages'
  

end
